#!/usr/bin/env php
<?php
require_once(__DIR__."/lib/dbmigrator.class.php");

$cwd = getcwd();
$configuration_file = implode(DIRECTORY_SEPARATOR, array($cwd, "build", "dbmigrator.config.php"));

if (empty($configuration_file) || !is_file($configuration_file)) {
	error("A valid dbmigrator.config.php could not be found in the project path. Giving up.", 1);
}

require_once($configuration_file);
try {
	$dbmigrator = new dbmigrator(DB_HOST, DB_NAME, DB_USER, DB_PASSWORD, DB_TYPE, OBJECT_PATH);
} catch (Exception $e) {
	error("dbmigrator failed to connect to the database.", 1);
}

$action = "default";
if (isset($argv[1])) {
	$action = strtolower($argv[1]);
}

switch ($action) {
	case "create": {
		if ($argc < 2) {
			error("Enter the name of at least one script to create.", 1);
		} else {
			$scripts = array_slice($argv, 2);
			$scripts_count = count($scripts);

			$x = 1;
			for ($i=0; $i<$scripts_count; ++$i) {
				$script_name = $dbmigrator->create($scripts[$i]);
				if (!$script_name) {
					error(sprintf("Failed to create migration script %s. You do not have permission to write the script template file.", $scripts[$i]), 1);
					break;
				}
				message(sprintf("Successfully created migration script %s", $script_name));
				
				if ($x !== $scripts_count) {
					sleep(2);
				}
				$x++;
			}
			echo(PHP_EOL);
		}
		break;
	}

	case "update": {
		$utc_timestamp = -1;
		if (3 == $argc) {
			$utc_timestamp = trim($argv[2]);
		}

		if ($dbmigrator->update($utc_timestamp)) {
			success("Successfully updated to latest migration script.", 0);
		} else {
			error("Failed to upgrade to latest migration.", 1);
		}
		
		break;
	}

	case "rollback": {
		$utc_timestamp = 0;
		if (3 == $argc) {
			$utc_timestamp = trim($argv[2]);
		}

		if ($dbmigrator->rollback($utc_timestamp)) {
			success("Successfully rolled back to latest migration script.", 0);
		} else {
			error("Failed to roll back to earliest migration.", 1);
		}
		
		break;
	}

	case "default": {
		message("Usage: dbmigrator [create,update,rollback] [<script-name>,[<timestamp>],[<timestamp>]]".PHP_EOL);
		break;
	}
}

exit(0);