CREATE TABLE _schema_changelog
(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
created DATETIME NOT NULL,
script_timestamp VARCHAR(16) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
script VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
set_up TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
tear_down TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL)
ENGINE=InnoDB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;
